### ISSUE TITLE
Bug: error with yakumo preinstall when creating template project

### ISSUE THREAD

**Issue by MirrorCY** [koishijs/koishi#948] opened 2023-01-23 20:01 UTC
### Describe the bug

And an additional line `$ yakumo preinstall || exit 0` appears when running `yarn` in the working directory.
View logs and screenshots for more detailed information.

### Steps to reproduce

1. Run `yarn create koishi` 
2. Check the output 
3. Enter the working directory 
4. Run `yarn` 
5. Check the output

### Expected behavior

1. Execute "yarn create koishi" correctly.
2. No additional lines are displayed when executing "yarn" in the working directory.

### Versions

- OS: windows 10
- yarn version: 1.22.19

### Additional context

![%AFS@)`1 M1H2S$OL9@$QLW](https://user-images.githubusercontent.com/37006258/214137855-45772757-aedd-40f0-9f72-d2bc2a1e928a.png)
![X{4$6R)O_4Q71OBB4(TV(Z4](https://user-images.githubusercontent.com/37006258/214137878-9be877a0-3f4d-4ddd-bd2f-eba3c8510145.png)

**Comment by lgc2333** [comment] 2023-01-23 22:39
https://github.com/koishijs/boilerplate/issues/7

**Comment by ilharp** [comment] 2023-01-24 07:18
Duplicate of https://github.com/koishijs/boilerplate/issues/7

这是意图的行为。如果有其他想法请在上方的 issue 中参与讨论。

**Closed by ilharp** 2023-01-24 07:18 UTC
Labels: bug
