### ISSUE TITLE
Bug: Status code 400 (It seems that the token expired) for feishu adapter

### ISSUE THREAD

**Issue by TimeBather** [koishijs/koishi#1009] opened 2023-03-06 08:40 UTC
### Describe the bug

When the bot was sending the message to the server, the koishi throw an error:
```
2023-03-06 16:29:27 [W] session AxiosError: Request failed with status code 400
```
It appear after my bot started for about half day. It seems that this error is caused by the token expiration.

### Steps to reproduce

 - Add a feishu adapter , and register a bot with **production enviornment ** in the feishu developer console
 - Add configures in the feishu adapter
 - Wait for about half day or one day

### Expected behavior

 - Send the message correctly

### Screenshots

```
2023-03-06 16:29:27 [W] session AxiosError: Request failed with status code 400
                            at settle (/usr/koishi/sumka-server/node_modules/axios/dist/node/axios.cjs:1268:12)
                            at IncomingMessage.handleStreamEnd (/usr/koishi/sumka-server/node_modules/axios/dist/node/axios.cjs:2446:11)
                            at IncomingMessage.emit (node:events:525:35)
                            at endReadableNT (node:internal/streams/readable:1359:12)
                            at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

No feishu api server log detected. Here is the feishu requester log:
```
{
  "eventId": "64*******************eb",
  "success": "success",
  "appId": "cli_************",
  "tenantKey": "2***********f",
  "eventType": "im.message.receive_v1",
  "hookType": 1,
  "address": "http://************/adapters/feishu",
  "retryCnt": "-",
  "costMills": 121,
  "errorInfo": "",
  "httpCode": 200,
  "eventTime": "1***********2"
}
```

### Versions

- OS: Linux , Ubuntu
- Platform: Feishu
- Node version: 16
- Koishi version: 4.11.9(Newest when I sending this issue)
- @koishijs/plugin-adapter-feishu : 1.2.2 

### Additional context

None

**Comment by shigma** [comment] 2023-03-06 16:41
duplicate of #1008?

**Comment by TimeBather** [comment] 2023-03-06 17:57
No , #1008 is a bug with **image sending** problem, not the authentication problem.

I am sure that it has enough permission for my bot because I use the same command to test it after I restart the bot and wait for half day. But it can send messages in the first condition but throw a 400 error in the last one.

**Comment by TimeBather** [comment] 2023-03-06 18:04
https://github.com/satorijs/satori/blob/c073802609a60579e43bb8d06a73fae0ee1b7e5c/adapters/feishu/src/bot.ts#LL43C4-L43C4
I search the references of `refershToken()` method in the satori project , and this method was only called by the `initialize` method. And another thing I found is that the getToken method did not read the expiration of the token . Is it the cause of this problem?

**Comment by MaikoTan** [comment] 2023-03-06 23:37
You're right. This is a point that could be optimised.
Axios allows you to add a `pre request` hook, so I think the token refreshing could be put here.

**Comment by MaikoTan** [comment] 2023-03-30 02:59
Resolved in https://github.com/satorijs/satori/pull/81

**Closed by MaikoTan** 2023-03-30 02:59 UTC
Labels: bug
